image:
  name: hashicorp/terraform:1.12.2
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin/:/usr/local/bin:/usr/sbin/:/usr/bin:/sbin:/bin'
  - 'AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)'
  - 'AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)'
before_script:
- rm -rf .terraform*
- terraform --version
- cat /etc/os*
- |
  cat <<EOF > terraform.tfvars
  aws_access_key = "${AWS_ACCESS_KEY_ID}"
  aws_secret_key = "${AWS_SECRET_ACCESS_KEY}"
  key_name       = "${KEY_NAME}"
  vpc_id         = "${VPC}"
  EOF
- terraform init
- terraform import aws_security_group.allow_all sg-0d4fd440a9cc94e8a || echo "Already imported"

stages:
- validate
- plan
- apply

validate-plan:
  stage: validate
  script:
  - terraform validate

plan-script:
  stage: plan
  script:
  - terraform plan

apply-code:
  stage: apply
  script:
  - terraform apply -auto-approve
  dependencies:
  - plan-script
